# Geometric Manipulations {geometries}

Simple feature geometries can be queried for properties, combined
into new geometries, and combinations of geometries can be queried
for properties. This chapter will give an overview of the operations
offered by `sf`.

We can categorise operations in terms of what they take as input,
and what they give as output. In terms of input we have operations
that take

* a single geometry (unary operations)
* a pair of geometries (binary operations)
* a set of geometries (n-ary operations)

and in terms of what is returned, we distinguish

* predicates, returning a logical asserting a certain property is `TRUE`
* measures, returning a numeric value (possibly with measurement unit)
* operations that return a new geometry, or a set of geometries

We will now go through all combinations.

## Unary Operations 

### Unary predicates

`st_is_simple`
`st_is_valid`
`st_is_longlat` 

`st_is` 

`==` `!=` : `st_equals`

### Unary measures
`st_dimension` 
`st_area` 
`st_length` 
`st_geohash`
`st_geometry_type`

### Unary operations returning a geometry

`st_centroid`
`st_buffer`
`st_jitter` 
`st_wrap_dateline`

`st_boundary`
`st_convex_hull`
`st_line_merge` merges, on a per-feature basis, connecting `LINESTRING` elements of a `MULTILINESTRING` into longer `LINESTRING`s.
`st_make_valid`
`st_node`
`st_point_on_surface`
`st_polygonize`
`st_segmentize`
`st_simplify`
`lwgeom::st_split`
`st_transform`
`st_triangulate`
`st_voronoi`

`st_zm`

`st_collection_extract`
`st_cast`

Ops: + - (unary, binary)

Ops: * / (sfg, Matrix)

## Binary Operations 

### Binary predicates

`st_contains`
`st_contains_properly`
`st_covered_by`
`st_covers`
`st_crosses` `st_disjoint` `st_equals` `st_equals_exact` `st_intersects`
`st_is_within_distance` `st_within` `st_touches` `st_overlaps`

### Binary measures

`st_distance`
`st_relate`

### Binary operations returning a geometry

`st_intersection`  `&`
`st_union`  `|`
`st_difference`  '/'
`st_sym_differenc`  '%/%'

## N-ary Operations 

### N-ary operations returning a geometry

For n-ary operations, we have only two, n-ary `st_intersection` and `st_difference`,
which both return geometries, in case of `st_intersection` along with some properties
for each of the geometry.

`st_make_grid`
`st_graticule`

## Warnings for longitude/latitude geometries

In st_centroid.sfc(st_geometry(x), of_largest_polygon = of_largest_polygon) :
  st_centroid does not give correct centroids for longitude/latitude data

How serious is this?
