# Statistical modelling of spatial data {#sec-modelling}

\index{statistical models}

So far, in this book we mostly addressed the problem of _describing_
data, e.g. by logical geometrical predicates or transformations that
involved geometries, or by summary measures or by plots depicting
variability in the geometry data or in feature attributes.

Statistical modelling aims at going beyond describing the data:
it considers the data as a sample drawn from a population, and
tries to make assessments (inference) about the population sampled
from, for instance by quantifying relationships between variables,
estimating population parameters, and predicting the outcome of
observations that could have been taken but weren't, as is the case
in interpolation. This is usually done by adopting a model for the
data, where for instance observations are decompsed as follows:

$$
\mbox{observed} = \mbox{explained} + \mbox{remainder}
$$ {#eq-model}

where ``explained'' typically uses external variables (predictors,
covariates, in machine learning confusingly also called features)
that are related to the observed variable and some kind of regression
model to translate into variability of the observed variable, and
``remainder'' is remaining variability that could not be explained.
Interest may focus on the nature and magnitude or the relations
between predictors and the observed variable, or in predicting
new observations.


