# Spatial Regression



[@whittle:54]

[@CliffOrd:72; @cliff+ord:73]

[@besag:74]
[@ord:75; hepple:76]

[@ripley:81; @ripley:88; @Cressie:1993]


## Spatial regression with spatial weights

[@cliff+ord:73; @cliff+ord:81; @a88]

[@WallerGotway:2004]


[@wall:04]


[@bivand17]

```{r}
library(sf)
```
```{r}
boston_506 <- st_read(system.file("shapes/boston_tracts.shp", package="spData")[1])
```


[@brookesetal:17]

```{r}
nb_q <- spdep::poly2nb(boston_506)
lw_q <- spdep::nb2listw(nb_q, style="W")
```


```{r, echo=FALSE}
agg_96 <- list(as.character(boston_506$NOX_ID))
boston_96 <- aggregate(boston_506[, "NOX_ID"], by=agg_96, unique)
boston_96 <- st_cast(boston_96, "MULTIPOLYGON")
nb_q_96 <- spdep::poly2nb(boston_96)
lw_q_96 <- spdep::nb2listw(nb_q_96)
```

```{r}
boston_96$units <- aggregate(boston_506$units, agg_96, sum)$x
boston_96$cu5k <- aggregate(boston_506$cu5k, agg_96, sum)$x
boston_96$c5_7_5 <- aggregate(boston_506$c5_7_5, agg_96, sum)$x
boston_96$C7_5_10 <- aggregate(boston_506$C7_5_10, agg_96, sum)$x
boston_96$C10_15 <- aggregate(boston_506$C10_15, agg_96, sum)$x
boston_96$C15_20 <- aggregate(boston_506$C15_20, agg_96, sum)$x
boston_96$C20_25 <- aggregate(boston_506$C20_25, agg_96, sum)$x
boston_96$C25_35 <- aggregate(boston_506$C25_35, agg_96, sum)$x
boston_96$C35_50 <- aggregate(boston_506$C35_50, agg_96, sum)$x
boston_96$co50k <- aggregate(boston_506$co50k, agg_96, sum)$x
```


[@lee:13]

[@umlaufetal:15]
[@wood:17]

[@smith:09] [@smith+lee12]



[@mur+angulo:06]
[@burridge:81; @bivand:84]

[@bivand:02; @goulardetal:17]
[@suesse:18]


[@fingleton:99]

[@pace+lesage:08]

[@lesage+pace:09]
[@elhorst:10]
[@bivand:12]
[@halleck-vega+elhorst:15]

[@mcmillen:13]


## Estimators

[@ord:75]

[@piras:10]
[@millo+piras:12]

[@bivand+piras:15]

## Handling the log determinant term

[@bivandetal13]

[@pace+barry:97a; @pace+barry:97b; @pace+barry:97c; @pace+barry:97d]


## Impacts

[@lesage+pace:09]
[@elhorst:10]
[@bivand:12]
[@halleck-vega+elhorst:15]

## Multilevel models with spatial weights

[@bivandetal17a]
[@alam-ronnegard-shen:2015]