project:
  type: book

book:
  title: "Spatial Data Science"
  subtitle: "with applications in R"
  author: "Edzer Pebesma, Roger Bivand"
  date: "10/17/2022"
  site-url: https://r-spatial.org/book/
  repo-url: https://github.com/edzer/sdsr/
  repo-branch: main
  repo-actions: [edit]
  chapters:
    - index.qmd
    - part: part-1.qmd
      chapters:
        - 01-hello.qmd
        - 02-Spaces.qmd
        - 03-Geometries.qmd
        - 04-Spherical.qmd
        - 05-Attributes.qmd
        - 06-Cubes.qmd
    - part: part-2.qmd
      chapters:
        - 07-Introsf.qmd
        - 08-Plotting.qmd
        - 09-Large.qmd
    - part: part-3.qmd
      chapters:
        - 10-Models.qmd
        - 11-PointPattern.qmd
        - 12-Interpolation.qmd
        - 13-Geostatistics.qmd
        - 14-Areal.qmd
        - 15-Measures.qmd
        - 16-SpatialRegression.qmd
        - 17-Econometrics.qmd
  appendices:
    - sp-raster.qmd
    - rbasics.qmd
    - references.qmd

bibliography: 
  - packages.bib
  - book.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#" 
    R.options:
      knitr.graphics.auto_pdf: true
      dplyr.print_min: 6
      dplyr.print_max: 6
      stars.crs: 17
      digits: 3

format:
  html:
    number-depth: 2
    theme: cosmo
    code-fold: false
    code-summary: "Code"
    knitr:
      opts_chunk:
        out.width: 100%
        R.options:
          width: 68
  pdf: 
    documentclass: krantz
    include-in-header:
      text: |
        \usepackage{imakeidx}
        \makeindex
        \makeindex[name=function,title={Index of functions}]
    include-after-body: 
      text: |
        \printindex
        \printindex[function]
    pdf-engine: pdflatex
    keep-tex: true
    collapse: true
    knitr:
      opts_chunk:
        out.width: 80%
        R.options:
          width: 62
