# Preface {.unnumbered}

```{r echo=FALSE,eval=FALSE}
knitr::write_bib(c(
  "abind",
  "classInt",
  "colorspace",
  "dbscan",
  "dbscan",
  "ecmwfr",
  "gdalcubes",
  "gdalUtilities",
  "ggplot2",
  "ggspatial",
  "gstat",
  "hglm",
  "HSAR",
  "igraph",
  "INLA",
  "lme4",
  "lwgeom",
  "mapsf",
  "mapview",
  "Matrix",
  "mgcv",
  "osmar", 
  "osmdata",
  "R2BayesX",
  "raster",
  "RColorBrewer",
  "rgee",
  "rgeoda",
  "rnaturalearth",
  "rstac",
  "s2",
  "sfnetworks",
  "sf", 
  "sp",
  "spacetime",
  "spatialreg",
  "spatstat",
  "spData",
  "spdep",
  "splm",
  "stars",
  "stcos",
  "stplanr", 
  "stpp", 
  "terra",
  "tidyverse",
  "tmap",
  "tsibble",
  "units",
  "viridis"
  ), "packages.bib", width = 60)
```

Data science is concerned with finding answers to questions on the
basis of available data, and communicating that effort. Besides
showing the results, this communication involves sharing the data
used, but also exposing the path that led to the answers in a
comprehensive and reproducible way. It also acknowledges the fact 
that available data may not be sufficient to answer questions, and 
that any answers are conditional on the data collection or sampling 
protocols employed.

\index{data science}
\index{spatial data science}

This book introduces and explains the concepts underlying
_spatial_ data: points, lines, polygons, rasters, coverages, geometry
attributes, data cubes, reference systems, as well as higher-level
concepts including how attributes relate to geometries and how
this affects analysis. The relationship of attributes to geometries
is known as support, and changing support also changes the 
characteristics of attributes. Some data generation processes are
continuous in space, and may be observed everywhere. Others are 
discrete, observed in tesselated containers. In modern spatial data
analysis, tesellated methods are often used for all data, extending 
across the legacy partition into point process, geostatistical and 
lattice models. It is support (and the understanding of support) that
underlies the importance of spatial representation. The book aims 
at data scientists who want to get a grip on using spatial data 
in their analysis. To exemplify how to do things, it uses R.
In future editions we hope to extend this with examples using Python
[see e.g. @bivand:22] and Julia.

It is often thought that spatial data boils down to having
observations' longitude and latitude in a dataset, and treating these
just like any other variable. This carries the risk of missed 
opportunities and meaningless analyses. For instance,

* coordinate pairs really are pairs, and lose much of their meaning 
when treated independently
* rather than having point locations, observations are often 
associated with spatial lines, areas, or grid cells
* spatial distances between observations are often not well
represented by straight-line distances, but by great circle
distances, distances through networks, or by measuring the effort
it takes getting from A to B

We introduce the concepts behind spatial data, coordinate reference
systems, spatial analysis, and introduce a number of packages,
including `sf` [@rjsf; @R-sf], `stars` [@R-stars], `s2` [@R-s2]
and `lwgeom` [@R-lwgeom], 
as well as a number of spatial `tidyverse` [@R-tidyverse] extensions, and a number of
spatial analysis and visualisation packages that can be used with these packages,
including `gstat` [@R-gstat], `spdep` [@R-spdep], `spatialreg` [@R-spatialreg], `spatstat` [@R-spatstat],
`tmap` [@R-tmap] and `mapview` [@R-mapview].

## Acknowledgements {-}

We are grateful to the entire r-spatial comunity, especially those who

* developed r-spatial packages or contributed to their development
* contributed to discussions on twitter `#rspatial` or GitHub 
* brought comments or asked questions in courses, summer
schools or conferences.

We are in particular grateful to Dewey Dunnington for implementing
the `s2` package, and for active contributions from Sahil Bhandari,
Jonathan Bahlmann for preparing the figures in @sec-datacube,
Claus Wilke, Jakub Nowosad, the "Spatial Data Science with R"
classes of 2021 and 2022, and to those who actively contributed
with GitHub issues, pull requests or discussions:

* to the book repository (Nowosad, jonathom, JaFro96,
singhkpratham, liuyadong, hurielreichel, PPaccioretti, Robinlovelace,
Syverpet, jonas-hurst, angela-li, ALanguillaume, florisvdh,
ismailsunni, andronaco),
* to the sf repository (aecoleman, agila5, andycraig, angela-li,
ateucher, barryrowlingson, bbest, BenGraeler, bhaskarvk, Bisaloo,
bkmgit, christophertull, chrisyeh96, cmcaine, cpsievert, daissi,
dankelley, DavisVaughan, dbaston, dblodgett-usgs, dcooley,
demorenoc, dpprdan, drkrynstrng, etiennebr, famuvie, fdetsch,
florisvdh, gregleleu, hadley, hughjonesd,
huizezhang-sherry, jeffreyhanson, jeroen, jlacko, joethorley,
joheisig, JoshOBrien, jwolfson, kadyb, karldw, kendonB, khondula,
KHwong12, krlmlr, lambdamoses, lbusett, lcgodoy, lionel-, loicdtx,
marwahaha, MatthieuStigler, mdsumner, MichaelChirico, microly,
mpadge, mtennekes, nikolai-b, noerw, Nowosad, oliverbeagley, Pakillo,
paleolimbot, pat-s, PPaccioretti, prdm0, ranghetti, rCarto, renejuan,
rhijmans, rhurlin, rnuske, Robinlovelace, robitalec, rubak, rundel,
statnmap, thomasp85, tim-salabim, tyluRp, uribo, Valexandre,
wibeasley, wittja01, yutannihilation, Zedseayou), 
* to the stars repository (a-benini, ailich, ateucher, btupper,
dblodgett-usgs, djnavarro, ErickChacon, ethanwhite, etiennebr, flahn,
floriandeboissieu, gavg712, gdkrmr, jannes-m, jeroen, JoshOBrien,
kadyb, kendonB, mdsumner, michaeldorman, mtennekes, Nowosad, pat-s,
PPaccioretti, przell, qdread, Rekyt, rhijmans, rubak, rushgeo,
statnmap, uribo, yutannihilation),
* to the s2 repository (kylebutts, spiry34, jeroen, eddelbuettel)

