---
title: "Spatial Data Science"
subtitle: "with applications in R"
author: ["Edzer Pebesma, Roger Bivand"]
date: "`r Sys.Date()`"
description: "description_xx"
github-repo: edzer/sdsr
bibliography: [book.bib, packages.bib]
link-citations: yes
site: bookdown::bookdown_site
output:
  html_document:
    code_folding: hide
  pdf_book: default
documentclass: book
biblio-style: apalike
always_allow_html: yes
---

```{r echo=FALSE}
knitr::write_bib(c(
  "abind",
  "classInt",
  "colorspace",
  "gdalcubes",
  "gstat",
  "ggplot2",
  "ggspatial",
  "lwgeom",
  "osmar", 
  "raster",
  "rgee",
  "ecmwfr",
  "rnaturalearth",
  "RColorBrewer",
  "raster",
  "rstac",
  "sf", 
  "sp",
  "spacetime",
  "spatstat", #-->> generates too many authors!! FIXME: update before submit!
  "spdep",
  "splm",
  "stars",
  "stcos",
  "stplanr", 
  "terra",
  "tidyverse",
  "tsibble",
  "viridis",
  "units",
  "xts",
  "s2",
  "tmap",
  "mapview"
  ), "packages.bib", width = 60)
```

# Preface {-}

Data science is concerned with finding answers to questions on the
basis of available data, and communicating that effort. Besides
showing the results, this communication involves sharing the data
used, but also exposing the path that led to the answers in a
comprehensive and reproducible way. It also acknowledges the fact 
that available data may not be sufficient to answer questions, and 
that any answers are conditional on the data collection or sampling 
protocols employed.

This book introduces and explains the concepts underlying
_spatial_ data: points, lines, polygons, rasters, coverages, geometry
attributes, data cubes, reference systems, as well as higher-level
concepts including how attributes relate to geometries and how
this affects analysis. The relationship of attributes to geometries
is known as support, and changing support also changes the 
characteristics of attributes. Some data generation processes are
continuous in space, and may be observed everywhere. Others are 
discrete, observed in tesselated containers. In modern spatial data
analysis, tesellated methods are often used for all data, extending 
across the legacy partition into point process, geostatistical and 
lattice models. It is support (and the understanding of support) that
underlies the importance of spatial representation. The book aims 
at data scientists who want to get a grip on using spatial data 
in their analysis. To exemplify how to do things, it uses R.

It is often thought that spatial data boils down to having
observations' longitude and latitude in a dataset, and treating these
just like any other variable. This carries the risk of missed 
opportunities and meaningless analyses. For instance,

* coordinate pairs really are pairs, and lose much of their meaning 
when treated independently
* rather than having point locations, observations are often 
associated with spatial lines, areas, or grid cells
* spatial distances between observations are often not well
represented by straight-line distances, but by great circle
distances, distances through networks, or by measuring the effort
it takes getting from A to B

We introduce the concepts behind spatial data, coordinate reference
systems, spatial analysis, and introduce a number of packages,
including `sf` [@rjsf; @R-sf], `stars` [@R-stars], `s2` [@R-s2]
and `lwgeom` [@R-lwgeom], 
as well as a number of `tidyverse` [@R-tidyverse] extensions, and a number of
spatial analysis and visualisation packages that can be used with these packages,
including `gstat` [@R-gstat], `spdep` [@R-spdep], `spatialreg` [@R-spatialreg], `spatstat` [@R-spatstat],
`tmap` [@R-tmap] and `mapview` [@R-mapview].

```{asis echo=knitr::is_latex_output()}
The first part of this book introduces concepts of spatial data science,
and uses R only to generate text output or figures. The R code used for
this is not shown, as it would distract from the message. The online
version of this book contains the R sections, which can be unfolded
on demand and copied into the clipboard for execution and experimenting.
The second part of this book explains how the concepts introduced in
part I are dealt with using R, and deals with basic handling and plotting
of spatial and spatiotemporal data. Part III is dedicated to statistical
modelling of spatial data.
```

```{asis echo=!knitr::is_latex_output()}
This work is licensed under the
[Attribution-NonCommercial-NoDerivatives
4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode)
International License.
```

