# R for Spatial Data Science

The second part of this book explains how the concepts introduced
in the first part are dealt with using R. @sec-sf deals with basic
handling of spatial data: reading, writing, subsetting, selecting
by spatial predicates, geometry transformers like buffers or
intersections, raster-vector and vector-raster conversion, handling
of data cubes, spherical geometry, coordinate transformations and
conversions. This is followed by a chapter dedicated to plotting
of spatial and spatiotemporal data with base plot, and packages
`ggplot2`, `tmap` and `mapview`. The chapter deals with projection,
colours, color breaks, graticules, graphic elements on maps like
legends, and interactive maps.  @sec-large discusses approaches
to handle large vector or raster datasets or data cubes, where
"large" either means too large to fit in memory or too large to
download.

The material covered in this part is not meant as a complete tutorial
nor a manual of the packages covered, but rather as an explanatin
and illustration of a number of common workflows. More complete
and detailed information is found in the package documentation, in
particular in the package vignettes for packages `sf` and `stars`.
Links to them are found on the CRAN landing pages of the packages.
