# Spatial Data

The first part of this book introduces concepts of spatial data
science: maps, projections, vector and raster data structures,
software, attributes and support, and data cubes.  This part uses
R only to generate text output or figures. The R code for this
is not shown or explained, as it would distract from the message:
Part II focuses on the use of R. The online version of this book,
found at [https://r-spatial.org/book/](https://r-spatial.org/book)
contains the R code at the place where it is used in hidden sections
that can be unfolded on demand and copied to the clipboard for
execution and experimenting.  Output from R code uses code font
and has lines starting with a `#`, as in

```{r codesection, echo=!knitr::is_latex_output()}
#| collapse: false
#| code-fold: true
library(sf)
```

::: {.content-visible when-format="html"}

Some of the code sections (e.g., in @sec-datacube) contain code
written to generate figures with R not relevant to the subject matter
of the book. Code sections relevant to data analysis should be easy
to follow when understanding R at the level of, say, [R for Data
Science](http://r4ds.had.co.nz/) [@r4ds].

:::

More detailed explanation of R code to solve spatial data science
problems starts in the second part of this book. @sec-rbasics
contains a short, elementary explanation of R data structures,
@advr gives a more extensive treatment on this.
